web:
 image: nginx:latest
 ports:
 - "8090:80"
 volumes:
 - ./code/ocs-uat:/opt/WebRoot/ocs-uat
 - ./code/ocs-test:/opt/WebRoot/ocs-test
 - ./nginx/nginx.conf:/etc/nginx/nginx.conf
 - ./nginx/ocs-uat.conf:/etc/nginx/conf.d/ocs-uat.conf
 - ./nginx/ocs-test.conf:/etc/nginx/conf.d/ocs-test.conf
 links:
 - php
php:
 image: docker.cvte.com/ocslib/php:latest
 ports:
 - "9000"
 volumes:
 - ./code/ocs-uat:/opt/WebRoot/ocs-uat
 - ./code/ocs-test:/opt/WebRoot/ocs-test
 - ./php/conf/ocs.ini:/usr/local/etc/php/conf.d/ocs.ini
 - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
redis:
 image: redis
 ports:
 - "6379:6379"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
  - PMA_ARBITRARY=1
  - PMA_HOST=rdstest.gz.cvte.cn
  restart: always
  ports:
  - 8080:80
kafka:
 image: wurstmeister/kafka
 links:
 - zoo
 ports:
 - "9092:9092"
 environment:
   KAFKA_LOG_DIRS: /kafka
   KAFKA_BROKER_ID: 1
   KAFKA_CREATE_TOPICS: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2
   KAFKA_ADVERTISED_HOST_NAME: 10.0.2.15
   KAFKA_ADVERTISED_PORT: 9092
   KAFKA_ZOOKEEPER_CONNECT: zoo:2181
zoo:
  image: zookeeper
  restart: always
  ports:
  - 2181:2181
  environment:
   ZOO_MY_ID: 1
